AWSTemplateFormatVersion: "2010-09-09"
Description: EC2-Instanze mit offenen Ports für HTTP und SSH, mit Ubuntu als BS

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-080e1f13689e07408
      KeyName: DevOps
      SecurityGroupIds:
        - sg-0d50e4cab37c45308
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt update
          sudo apt install docker.io -y
          sudo service docker start
          # Enable Docker on boot
          sudo systemctl enable docker
          sudo docker create network app_network
      Tags:
        - Key: Name
          Value: DevOpsTest

Outputs:
  InstanceId:
    Description: Instance ID of the created EC2 instance
    Value: !Ref EC2Instance
