name: Continuous Deployment for the DevOps Quotes API

on:
  workflow_dispatch:
  push:
    branches: [master]

env:
  DOCKER_IMAGE_NAME: mhouney/quote_magician_devops_api:latest

jobs:
  build-and-deploy-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t mhouney/quote_magician_devops_api:latest .
          docker push mhouney/quote_magician_devops_api:latest
  deploy-to-aws-ec2:
    runs-on: ubuntu-latest
    needs: build-and-deploy-image
    steps:
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Deploy to AWS EC2
        run: |
          echo "${{ secrets.SSH_KEY }}" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@ec2-54-208-92-246.compute-1.amazonaws.com '

          cd ~/
          touch testfile.txt
          
