name: Continuous Deployment for the DevOps Quotes API

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Continuous Integration for the DevOps Quotes API"]
    branches: [master]
    types:
      - completed

env:
  DOCKER_IMAGE_NAME: mhouney/quote_magician_devops_api:latest
  PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  build-and-deploy-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_NAME }} .
          docker push ${{ env.DOCKER_IMAGE_NAME }}
  deploy-to-aws-ec2:
    runs-on: ubuntu-latest
    needs: build-and-deploy-image
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Deploy to AWS EC2 and start container
        run: |
          PRIVATE_KEY_FILE="private_key"
          echo "$PRIVATE_KEY" > $PRIVATE_KEY_FILE && chmod 600 $PRIVATE_KEY_FILE

          ssh -o StrictHostKeyChecking=no -i $PRIVATE_KEY_FILE ubuntu@${{ secrets.EC2_PUBLIC_IP_ADDRESS }} 'sudo docker compose down'

          ssh -o StrictHostKeyChecking=no -i $PRIVATE_KEY_FILE ubuntu@${{ secrets.EC2_PUBLIC_IP_ADDRESS }} 'sudo docker compose pull'

          ssh -o StrictHostKeyChecking=no -i $PRIVATE_KEY_FILE ubuntu@${{ secrets.EC2_PUBLIC_IP_ADDRESS }} 'sudo docker compose up -d'
