name: Continuous Deployment for the DevOps Quotes API

on:
  workflow_dispatch:
  push:
    branches: [master]

env:
  DOCKER_IMAGE_NAME: mhouney/quote_magician_devops_api:latest
  PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  build-and-deploy-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t mhouney/quote_magician_devops_api:latest .
          docker push mhouney/quote_magician_devops_api:latest
  deploy-to-aws-ec2:
    runs-on: ubuntu-latest
    needs: build-and-deploy-image
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Deploy to AWS EC2
        # env:
        #   MONGODB_ATLAS_USERNAME: ${{ secrets.MONGODB_ATLAS_USERNAME }}
        #   MONGODB_ATLAS_PASSWORD: ${{ secrets.MONGODB_ATLAS_PASSWORD }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@ec2-54-237-185-133.compute-1.amazonaws.com 'sudo docker pull mhouney/quote_magician_devops_api:latest'
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@ec2-54-237-185-133.compute-1.amazonaws.com 'sudo docker run -p 4000:4000 -d -e MONGODB_ATLAS_USERNAME=${{ secrets.MONGODB_ATLAS_USERNAME }} -e MONGODB_ATLAS_PASSWORD=${{ secrets.MONGODB_ATLAS_PASSWORD }} --name api-container mhouney/quote_magician_devops_api:latest'
